apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devspaces-side-container
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhn-support-agiertli-tenant/devspaces-side-container/devspaces-side-container@sha256:8b7ba8fc1bd1a7c66e13de263e129615abe833ebe702d9c4d013a9dd89cc3b87
        name: my-java-springboot
        resources: {}
status: {}
